### ISSUE TITLE
文字太宽, 可能会阅读时感觉不适.

### ISSUE THREAD

**Issue by drmingdrmer** [bsc-s2/bscweb#4]
![image](https://user-images.githubusercontent.com/44069/40470526-5183d0fa-5f66-11e8-912a-953bae59964e.png)

这样感觉好读点...
![image](https://user-images.githubusercontent.com/44069/40470605-8c3f1286-5f66-11e8-9c07-9daaa98054cb.png)

**Comment by adwerrd** [comment]
感觉这里改成两行 再加上扩大行距 显得更好看一些

**Comment by adwerrd** [comment]
![image](https://user-images.githubusercontent.com/8522625/40688508-f876464a-63d0-11e8-8610-75bf88c1a6c8.png)
现在是这个效果
